package com.bookvehicle.example.sr.model;

public enum NotificationType {
    BOOKING_ASSIGNED,
    BOOKING_ACCEPTED,
    TRIP_COMPLETED,
    TRIP_STARTED,
    PAYMENT_DONE,
    DRIVER_APPROVED,
    DRIVER_REJECTED,
    RENTAL_CREATED,
    RENTAL_ACCEPTED,
    RENTAL_REJECTED,
    RENTAL_CANCELLED,
    RENTAL_PAID,
    SOBER_CREATED,
    SOBER_ACCEPTED,
    SOBER_ARRIVED,
    SOBER_STARTED,
    SOBER_COMPLETED,
    SOBER_CANCELLED,
    SOBER_PAID,
    DEPOSIT_SUCCESS,
    WITHDRAW_REQUEST,
    WITHDRAW_APPROVED,
    WITHDRAW_REJECTED,
    GENERAL
}
